server:
  servlet:
    context-path: /rap
spring:
  datasource:
    url: jdbc:mysql://47.95.10.169:3306/rap?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql2019

